"""PR Manager — handles PR creation deterministically without AI context.

Gathers git context (commits, diff stats), builds PR title/description from
configurable templates, creates PR via Bitbucket API, and saves pr_url/pr_number
directly to the database.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re

from dataclasses import dataclass
from pathlib import Path

from engine.bitbucket_client import BitbucketClient
from engine.state import StateManager

logger = logging.getLogger(__name__)

DEFAULT_PR_TEMPLATE = """## Summary
${commit_descriptions}

## Changes
```
${diff_stat}
```

## Test Plan
- [ ] Tests pass locally
- [ ] Code reviewed

Generated by Task Ninja
"""

# Variables available in PR templates — shown in UI help text
PR_TEMPLATE_VARIABLES = {
    "${commit_bullets}": "Bulleted list of commit messages (- hash subject)",
    "${commit_descriptions}": "Full commit messages (subject + body), separated by ---",
    "${diff_stat}": "git diff --stat output (file list with +/- counts)",
    "${file_count}": "Number of files changed",
    "${additions}": "Lines added",
    "${deletions}": "Lines removed",
    "${jira_key}": "Jira ticket key (e.g. MC-1234)",
    "${summary}": "Jira ticket summary",
    "${branch_name}": "Git branch name",
    "${jira_url}": "Full Jira ticket URL",
}


@dataclass
class GitContext:
    """Git context gathered for PR creation."""

    branch_name: str
    commits: list[str]  # One-line commit messages (hash + subject)
    commit_bodies: list[str]  # Full commit messages (subject + body, trimmed)
    diff_stat: str  # Output of git diff --stat
    file_count: int
    additions: int
    deletions: int


@dataclass
class PrResult:
    """Result of a PR creation attempt."""

    success: bool
    pr_url: str | None = None
    pr_number: int | None = None
    pr_title: str | None = None
    error: str | None = None


class PrManager:
    """Creates PRs deterministically using git context + Bitbucket API."""

    def __init__(self, state: StateManager, bitbucket: BitbucketClient):
        self.state = state
        self.bitbucket = bitbucket

    @staticmethod
    def _resolve_git_cwd(worktree_path: str) -> str:
        """Return a valid git working directory.

        Prefers the worktree path itself, but falls back to ancestor
        directories (e.g. the main repo root) if the worktree was deleted
        while the push/PR was pending.
        """
        p = Path(worktree_path)
        if p.is_dir():
            return worktree_path
        # Walk up to find a directory that contains a .git entry
        for parent in p.parents:
            if parent.is_dir() and (parent / ".git").exists():
                logger.warning(
                    "Worktree %s missing — falling back to repo root %s",
                    worktree_path,
                    parent,
                )
                return str(parent)
        # Last resort: return original (will fail, but error is clear)
        return worktree_path

    async def create_pr_for_ticket(self, ticket_id: str) -> PrResult:
        """Full PR creation flow for a ticket.

        1. Gather git context (branch, commits, diff stats)
        2. Push branch to remote
        3. Build PR title and description from template
        4. Resolve reviewers
        5. Create PR via Bitbucket API
        6. Save pr_url/pr_number to ticket
        """
        ticket = await self.state.get_ticket(ticket_id)
        if not ticket:
            return PrResult(success=False, error="Ticket not found")

        if not ticket.worktree_path:
            return PrResult(success=False, error="No worktree path on ticket")

        if not ticket.branch_name:
            return PrResult(success=False, error="No branch name on ticket")

        # Resolve repository
        repo = None
        if ticket.repository_id:
            repo = await self.state.get_repository(ticket.repository_id)
        if not repo:
            # Try via run
            run = await self.state.get_run(ticket.run_id)
            if run and run.repository_id:
                repo = await self.state.get_repository(run.repository_id)

        if not repo:
            return PrResult(success=False, error="No repository configured for ticket")

        # Resolve parent branch
        parent_branch = ticket.parent_branch
        if not parent_branch:
            run = await self.state.get_run(ticket.run_id)
            parent_branch = (run.parent_branch if run else None) or repo.default_branch or "master"

        # Derive repo_slug from repo name or path
        repo_slug = self._derive_repo_slug(repo)
        if not repo_slug:
            return PrResult(success=False, error=f"Cannot derive repo slug from: {repo.name}")

        # 1. Gather git context
        try:
            git_ctx = await self._gather_git_context(
                ticket.worktree_path, ticket.branch_name, parent_branch
            )
        except RuntimeError as e:
            return PrResult(success=False, error=f"Failed to gather git context: {e}")

        # 2. Push branch
        try:
            await self._git_push(ticket.worktree_path, ticket.branch_name)
        except RuntimeError as e:
            return PrResult(success=False, error=f"Failed to push branch: {e}")

        # 3. Build title and description
        branch_type, jira_key = self._parse_branch(ticket.branch_name)
        title = self._build_title(
            repo.pr_title_format,
            branch_type=branch_type,
            ticket_key=ticket.jira_key,
            summary=ticket.summary or "",
        )
        description = self._build_description(
            repo.pr_template,
            git_ctx=git_ctx,
            jira_key=ticket.jira_key,
            summary=ticket.summary or "",
        )

        # 4. Resolve reviewers
        reviewers = await self._resolve_reviewers(repo, repo_slug)

        # 5. Create PR
        pr_data = await self.bitbucket.create_pr(
            repo_slug=repo_slug,
            title=title,
            source_branch=ticket.branch_name,
            destination_branch=parent_branch,
            description=description,
            reviewers=reviewers,
        )

        if not pr_data:
            return PrResult(success=False, error="Bitbucket API returned no data")

        pr_url = pr_data.get("url", "")
        pr_number = pr_data.get("id")

        # 6. Save to ticket
        await self.state.update_ticket(
            ticket_id,
            pr_url=pr_url,
            pr_number=pr_number,
        )

        logger.info(
            "Created PR #%s for %s: %s",
            pr_number, ticket.jira_key, pr_url,
        )

        return PrResult(
            success=True,
            pr_url=pr_url,
            pr_number=pr_number,
            pr_title=title,
        )

    def _derive_repo_slug(self, repo) -> str | None:
        """Derive Bitbucket repo slug from repository name or path."""
        # If name looks like a slug already (lowercase, hyphens)
        if repo.name and re.match(r"^[a-z0-9._-]+$", repo.name):
            return repo.name

        # Try extracting from path (last directory component)
        if repo.path:
            path_slug = Path(repo.path).name
            if path_slug:
                return path_slug.lower().replace(" ", "-")

        # Fallback: slugify the name
        if repo.name:
            return re.sub(r"[^a-z0-9-]", "-", repo.name.lower()).strip("-")

        return None

    async def _gather_git_context(
        self, worktree_path: str, branch: str, parent_branch: str
    ) -> GitContext:
        """Gather commits and diff stats from git."""
        cwd = self._resolve_git_cwd(worktree_path)

        # Get commit list (use explicit branch name so it works from any git dir)
        proc = await asyncio.create_subprocess_exec(
            "git", "log", f"origin/{parent_branch}..{branch}", "--oneline",
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        commits = [
            line.strip() for line in stdout.decode().strip().splitlines() if line.strip()
        ]

        # Get diff stat
        proc = await asyncio.create_subprocess_exec(
            "git", "diff", f"origin/{parent_branch}...{branch}", "--stat",
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        diff_stat = stdout.decode().strip()

        # Get shortstat for numbers
        proc = await asyncio.create_subprocess_exec(
            "git", "diff", f"origin/{parent_branch}...{branch}", "--shortstat",
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        shortstat = stdout.decode().strip()

        file_count = 0
        additions = 0
        deletions = 0
        # Parse "3 files changed, 42 insertions(+), 10 deletions(-)"
        m = re.search(r"(\d+) file", shortstat)
        if m:
            file_count = int(m.group(1))
        m = re.search(r"(\d+) insertion", shortstat)
        if m:
            additions = int(m.group(1))
        m = re.search(r"(\d+) deletion", shortstat)
        if m:
            deletions = int(m.group(1))

        # Get full commit messages (subject + body) for description
        _SEP = "---COMMIT_SEP---"
        proc = await asyncio.create_subprocess_exec(
            "git", "log", f"origin/{parent_branch}..{branch}",
            f"--format=%B{_SEP}",
            "--reverse",
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        raw_bodies = stdout.decode().split(_SEP)
        commit_bodies = [b.strip() for b in raw_bodies if b.strip()]

        return GitContext(
            branch_name=branch,
            commits=commits,
            commit_bodies=commit_bodies,
            diff_stat=diff_stat,
            file_count=file_count,
            additions=additions,
            deletions=deletions,
        )

    async def _git_push(self, worktree_path: str, branch: str) -> None:
        """Push branch to origin."""
        cwd = self._resolve_git_cwd(worktree_path)
        proc = await asyncio.create_subprocess_exec(
            "git", "push", "-u", "origin", branch,
            cwd=cwd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            err = stderr.decode().strip()
            # "Everything up-to-date" is fine
            if "up-to-date" not in err and "Everything" not in err:
                raise RuntimeError(err)

    def _parse_branch(self, branch_name: str) -> tuple[str, str]:
        """Extract type and ticket key from branch name.

        e.g. 'feat/MC-1234-add-feature' -> ('feat', 'MC-1234')
        """
        match = re.match(r"^([^/]+)/([A-Z]+-\d+)", branch_name)
        if match:
            return match.group(1), match.group(2)
        return "feat", ""

    def _build_title(
        self,
        title_format: str,
        branch_type: str,
        ticket_key: str,
        summary: str,
    ) -> str:
        """Build PR title from format string using ${variable} syntax."""
        # Truncate summary to keep title readable
        short_summary = summary[:80] if summary else "implementation"
        short_summary = short_summary.strip().rstrip(".")

        variables = {
            "${type}": branch_type,
            "${ticket}": ticket_key,
            "${summary}": short_summary,
        }

        result = title_format
        for var, value in variables.items():
            result = result.replace(var, value)

        return result

    def _build_description(
        self,
        template: str | None,
        git_ctx: GitContext,
        jira_key: str,
        summary: str,
    ) -> str:
        """Build PR description from template and git context.

        Uses ${variable} syntax for safe substitution — unknown variables
        are left as-is (no crashes), and curly braces in Markdown are safe.
        """
        tmpl = template or DEFAULT_PR_TEMPLATE

        # Build commit bullets (hash + subject, one per line)
        commit_bullets = "\n".join(f"- {c}" for c in git_ctx.commits) if git_ctx.commits else "- Initial implementation"

        # Build commit descriptions (full message per commit, separated by ---)
        if git_ctx.commit_bodies:
            commit_descriptions = "\n\n---\n\n".join(git_ctx.commit_bodies)
        else:
            commit_descriptions = commit_bullets

        # Build substitution map
        jira_url = f"https://jurnal.atlassian.net/browse/{jira_key}"
        variables = {
            "${commit_bullets}": commit_bullets,
            "${commit_descriptions}": commit_descriptions,
            "${diff_stat}": git_ctx.diff_stat or "No changes detected",
            "${file_count}": str(git_ctx.file_count),
            "${additions}": str(git_ctx.additions),
            "${deletions}": str(git_ctx.deletions),
            "${jira_key}": jira_key,
            "${summary}": summary,
            "${branch_name}": git_ctx.branch_name,
            "${jira_url}": jira_url,
        }

        result = tmpl
        for var, value in variables.items():
            result = result.replace(var, value)

        return result

    async def _resolve_reviewers(self, repo, repo_slug: str) -> list[dict]:
        """Resolve reviewer UUIDs from repo config or Bitbucket defaults."""
        # Try repo-configured reviewers first
        if repo.default_reviewers:
            try:
                emails = json.loads(repo.default_reviewers)
                if emails:
                    uuids = await self.bitbucket.resolve_reviewer_uuids(repo_slug, emails)
                    if uuids:
                        return uuids
            except (json.JSONDecodeError, TypeError):
                pass

        # Fallback to Bitbucket default reviewers
        defaults = await self.bitbucket.get_default_reviewers(repo_slug)
        return [{"uuid": r["uuid"]} for r in defaults if r.get("uuid")]
